// <auto-generated />
using System;
using APBD_Kolos_2_Poprawa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_Kolos_2_Poprawa.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MapId");

                    b.ToTable("Map");

                    b.HasData(
                        new
                        {
                            MapId = 1,
                            Name = "as",
                            Type = "ajsdas"
                        },
                        new
                        {
                            MapId = 2,
                            Name = "asas",
                            Type = "ajsdas12"
                        },
                        new
                        {
                            MapId = 3,
                            Name = "asdasdas",
                            Type = "ajsdasdasd"
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<decimal?>("BestRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("MapId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            BestRating = 2.7m,
                            MapId = 1,
                            MatchDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 2,
                            Team2Score = 3,
                            TournamentId = 1
                        },
                        new
                        {
                            MatchId = 2,
                            BestRating = 3.7m,
                            MapId = 2,
                            MatchDate = new DateTime(2021, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 3,
                            Team2Score = 5,
                            TournamentId = 2
                        },
                        new
                        {
                            MatchId = 3,
                            BestRating = 6.7m,
                            MapId = 3,
                            MatchDate = new DateTime(2021, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 4,
                            Team2Score = 6,
                            TournamentId = 3
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            BirthDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "a",
                            LastName = "b"
                        },
                        new
                        {
                            PlayerId = 2,
                            BirthDate = new DateTime(2021, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "c",
                            LastName = "d"
                        },
                        new
                        {
                            PlayerId = 3,
                            BirthDate = new DateTime(2021, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "e",
                            LastName = "f"
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.PlayerMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("MvPs")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerMatch");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            PlayerId = 1,
                            MvPs = 5,
                            Rating = 4.5m
                        },
                        new
                        {
                            MatchId = 2,
                            PlayerId = 2,
                            MvPs = 4,
                            Rating = 2.5m
                        },
                        new
                        {
                            MatchId = 3,
                            PlayerId = 3,
                            MvPs = 3,
                            Rating = 6.5m
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournament");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            EndDate = new DateTime(2021, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "asdas",
                            StartDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TournamentId = 2,
                            EndDate = new DateTime(2021, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "asdasa",
                            StartDate = new DateTime(2021, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TournamentId = 3,
                            EndDate = new DateTime(2021, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "asdasss",
                            StartDate = new DateTime(2021, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Match", b =>
                {
                    b.HasOne("APBD_Kolos_2_Poprawa.Models.Map", "Map")
                        .WithMany("Matches")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Kolos_2_Poprawa.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.PlayerMatch", b =>
                {
                    b.HasOne("APBD_Kolos_2_Poprawa.Models.Match", "Match")
                        .WithMany("PlayerMatches")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Kolos_2_Poprawa.Models.Player", "Player")
                        .WithMany("PlayerMatches")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Map", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Match", b =>
                {
                    b.Navigation("PlayerMatches");
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Player", b =>
                {
                    b.Navigation("PlayerMatches");
                });

            modelBuilder.Entity("APBD_Kolos_2_Poprawa.Models.Tournament", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
